CREATE TABLE authors (
    id CHAR(36) DEFAULT (UUID()) PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    bio TEXT DEFAULT NULL,
    birth_date DATE NOT NULL,
    nationality VARCHAR(90) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
