CREATE TABLE books (
    id CHAR(36) DEFAULT (UUID()) PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author_id CHAR(36) NOT NULL,
    publish_date DATE DEFAULT NULL,
    description TEXT NOT NULL,
    pages INT DEFAULT NULL,
    genre VARCHAR(30) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (author_id) REFERENCES authors(id) ON DELETE CASCADE
);
